/*
Trader Joe Dex API

<p>Discover DeFi with Trader Joe, a leading decentralized exchange. Trade a wide variety of tokens, earn rewards, and engage in secure, peer-to-peer transactions. Trader Joe makes DeFi easy and accessible.

API version: 1.0.0
Contact: public-api@traderjoexyz.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package traderjoesdk

import (
	"encoding/json"
	"fmt"
)

// checks if the ClaimableReward type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClaimableReward{}

// ClaimableReward struct for ClaimableReward
type ClaimableReward struct {
	Market               string            `json:"market"`
	Epoch                int32             `json:"epoch"`
	ClaimableRewards     []GetLBPairReward `json:"claimableRewards"`
	AdditionalProperties map[string]interface{}
}

type _ClaimableReward ClaimableReward

// NewClaimableReward instantiates a new ClaimableReward object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClaimableReward(market string, epoch int32, claimableRewards []GetLBPairReward) *ClaimableReward {
	this := ClaimableReward{}
	this.Market = market
	this.Epoch = epoch
	this.ClaimableRewards = claimableRewards
	return &this
}

// NewClaimableRewardWithDefaults instantiates a new ClaimableReward object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClaimableRewardWithDefaults() *ClaimableReward {
	this := ClaimableReward{}
	return &this
}

// GetMarket returns the Market field value
func (o *ClaimableReward) GetMarket() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Market
}

// GetMarketOk returns a tuple with the Market field value
// and a boolean to check if the value has been set.
func (o *ClaimableReward) GetMarketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Market, true
}

// SetMarket sets field value
func (o *ClaimableReward) SetMarket(v string) {
	o.Market = v
}

// GetEpoch returns the Epoch field value
func (o *ClaimableReward) GetEpoch() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Epoch
}

// GetEpochOk returns a tuple with the Epoch field value
// and a boolean to check if the value has been set.
func (o *ClaimableReward) GetEpochOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Epoch, true
}

// SetEpoch sets field value
func (o *ClaimableReward) SetEpoch(v int32) {
	o.Epoch = v
}

// GetClaimableRewards returns the ClaimableRewards field value
func (o *ClaimableReward) GetClaimableRewards() []GetLBPairReward {
	if o == nil {
		var ret []GetLBPairReward
		return ret
	}

	return o.ClaimableRewards
}

// GetClaimableRewardsOk returns a tuple with the ClaimableRewards field value
// and a boolean to check if the value has been set.
func (o *ClaimableReward) GetClaimableRewardsOk() ([]GetLBPairReward, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClaimableRewards, true
}

// SetClaimableRewards sets field value
func (o *ClaimableReward) SetClaimableRewards(v []GetLBPairReward) {
	o.ClaimableRewards = v
}

func (o ClaimableReward) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClaimableReward) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["market"] = o.Market
	toSerialize["epoch"] = o.Epoch
	toSerialize["claimableRewards"] = o.ClaimableRewards

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClaimableReward) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"market",
		"epoch",
		"claimableRewards",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClaimableReward := _ClaimableReward{}

	err = json.Unmarshal(data, &varClaimableReward)

	if err != nil {
		return err
	}

	*o = ClaimableReward(varClaimableReward)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "market")
		delete(additionalProperties, "epoch")
		delete(additionalProperties, "claimableRewards")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClaimableReward struct {
	value *ClaimableReward
	isSet bool
}

func (v NullableClaimableReward) Get() *ClaimableReward {
	return v.value
}

func (v *NullableClaimableReward) Set(val *ClaimableReward) {
	v.value = val
	v.isSet = true
}

func (v NullableClaimableReward) IsSet() bool {
	return v.isSet
}

func (v *NullableClaimableReward) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClaimableReward(val *ClaimableReward) *NullableClaimableReward {
	return &NullableClaimableReward{value: val, isSet: true}
}

func (v NullableClaimableReward) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClaimableReward) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
