/*
Trader Joe Dex API

<p>Discover DeFi with Trader Joe, a leading decentralized exchange. Trade a wide variety of tokens, earn rewards, and engage in secure, peer-to-peer transactions. Trader Joe makes DeFi easy and accessible.

API version: 1.0.0
Contact: public-api@traderjoexyz.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package traderjoesdk

import (
	"encoding/json"
	"fmt"
)

// PairVersion An enumeration.
type PairVersion string

// List of PairVersion
const (
	_0 PairVersion = "v2.0"
	_1 PairVersion = "v2.1"
	_2 PairVersion = "v2.2"
)

// All allowed values of PairVersion enum
var AllowedPairVersionEnumValues = []PairVersion{
	"v2.0",
	"v2.1",
	"v2.2",
}

func (v *PairVersion) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PairVersion(value)
	for _, existing := range AllowedPairVersionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PairVersion", value)
}

// NewPairVersionFromValue returns a pointer to a valid PairVersion
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPairVersionFromValue(v string) (*PairVersion, error) {
	ev := PairVersion(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PairVersion: valid values are %v", v, AllowedPairVersionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PairVersion) IsValid() bool {
	for _, existing := range AllowedPairVersionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PairVersion value
func (v PairVersion) Ptr() *PairVersion {
	return &v
}

type NullablePairVersion struct {
	value *PairVersion
	isSet bool
}

func (v NullablePairVersion) Get() *PairVersion {
	return v.value
}

func (v *NullablePairVersion) Set(val *PairVersion) {
	v.value = val
	v.isSet = true
}

func (v NullablePairVersion) IsSet() bool {
	return v.isSet
}

func (v *NullablePairVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePairVersion(val *PairVersion) *NullablePairVersion {
	return &NullablePairVersion{value: val, isSet: true}
}

func (v NullablePairVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePairVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
