/*
Trader Joe Dex API

<p>Discover DeFi with Trader Joe, a leading decentralized exchange. Trade a wide variety of tokens, earn rewards, and engage in secure, peer-to-peer transactions. Trader Joe makes DeFi easy and accessible.

API version: 1.0.0
Contact: public-api@traderjoexyz.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package traderjoesdk

import (
	"encoding/json"
	"fmt"
)

// checks if the UserBinPositionTokenWrapper type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserBinPositionTokenWrapper{}

// UserBinPositionTokenWrapper struct for UserBinPositionTokenWrapper
type UserBinPositionTokenWrapper struct {
	Address              string   `json:"address"`
	Name                 string   `json:"name"`
	Symbol               string   `json:"symbol"`
	Decimals             int32    `json:"decimals"`
	Amount               float32  `json:"amount"`
	AmountRaw            string   `json:"amountRaw"`
	Price                float32  `json:"price"`
	PriceUsd             *float32 `json:"priceUsd,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UserBinPositionTokenWrapper UserBinPositionTokenWrapper

// NewUserBinPositionTokenWrapper instantiates a new UserBinPositionTokenWrapper object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserBinPositionTokenWrapper(address string, name string, symbol string, decimals int32, amount float32, amountRaw string, price float32) *UserBinPositionTokenWrapper {
	this := UserBinPositionTokenWrapper{}
	this.Address = address
	this.Name = name
	this.Symbol = symbol
	this.Decimals = decimals
	this.Amount = amount
	this.AmountRaw = amountRaw
	this.Price = price
	return &this
}

// NewUserBinPositionTokenWrapperWithDefaults instantiates a new UserBinPositionTokenWrapper object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserBinPositionTokenWrapperWithDefaults() *UserBinPositionTokenWrapper {
	this := UserBinPositionTokenWrapper{}
	return &this
}

// GetAddress returns the Address field value
func (o *UserBinPositionTokenWrapper) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *UserBinPositionTokenWrapper) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *UserBinPositionTokenWrapper) SetAddress(v string) {
	o.Address = v
}

// GetName returns the Name field value
func (o *UserBinPositionTokenWrapper) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserBinPositionTokenWrapper) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserBinPositionTokenWrapper) SetName(v string) {
	o.Name = v
}

// GetSymbol returns the Symbol field value
func (o *UserBinPositionTokenWrapper) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *UserBinPositionTokenWrapper) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *UserBinPositionTokenWrapper) SetSymbol(v string) {
	o.Symbol = v
}

// GetDecimals returns the Decimals field value
func (o *UserBinPositionTokenWrapper) GetDecimals() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Decimals
}

// GetDecimalsOk returns a tuple with the Decimals field value
// and a boolean to check if the value has been set.
func (o *UserBinPositionTokenWrapper) GetDecimalsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decimals, true
}

// SetDecimals sets field value
func (o *UserBinPositionTokenWrapper) SetDecimals(v int32) {
	o.Decimals = v
}

// GetAmount returns the Amount field value
func (o *UserBinPositionTokenWrapper) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *UserBinPositionTokenWrapper) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *UserBinPositionTokenWrapper) SetAmount(v float32) {
	o.Amount = v
}

// GetAmountRaw returns the AmountRaw field value
func (o *UserBinPositionTokenWrapper) GetAmountRaw() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmountRaw
}

// GetAmountRawOk returns a tuple with the AmountRaw field value
// and a boolean to check if the value has been set.
func (o *UserBinPositionTokenWrapper) GetAmountRawOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountRaw, true
}

// SetAmountRaw sets field value
func (o *UserBinPositionTokenWrapper) SetAmountRaw(v string) {
	o.AmountRaw = v
}

// GetPrice returns the Price field value
func (o *UserBinPositionTokenWrapper) GetPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *UserBinPositionTokenWrapper) GetPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *UserBinPositionTokenWrapper) SetPrice(v float32) {
	o.Price = v
}

// GetPriceUsd returns the PriceUsd field value if set, zero value otherwise.
func (o *UserBinPositionTokenWrapper) GetPriceUsd() float32 {
	if o == nil || IsNil(o.PriceUsd) {
		var ret float32
		return ret
	}
	return *o.PriceUsd
}

// GetPriceUsdOk returns a tuple with the PriceUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserBinPositionTokenWrapper) GetPriceUsdOk() (*float32, bool) {
	if o == nil || IsNil(o.PriceUsd) {
		return nil, false
	}
	return o.PriceUsd, true
}

// HasPriceUsd returns a boolean if a field has been set.
func (o *UserBinPositionTokenWrapper) HasPriceUsd() bool {
	if o != nil && !IsNil(o.PriceUsd) {
		return true
	}

	return false
}

// SetPriceUsd gets a reference to the given float32 and assigns it to the PriceUsd field.
func (o *UserBinPositionTokenWrapper) SetPriceUsd(v float32) {
	o.PriceUsd = &v
}

func (o UserBinPositionTokenWrapper) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserBinPositionTokenWrapper) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["name"] = o.Name
	toSerialize["symbol"] = o.Symbol
	toSerialize["decimals"] = o.Decimals
	toSerialize["amount"] = o.Amount
	toSerialize["amountRaw"] = o.AmountRaw
	toSerialize["price"] = o.Price
	if !IsNil(o.PriceUsd) {
		toSerialize["priceUsd"] = o.PriceUsd
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserBinPositionTokenWrapper) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"name",
		"symbol",
		"decimals",
		"amount",
		"amountRaw",
		"price",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserBinPositionTokenWrapper := _UserBinPositionTokenWrapper{}

	err = json.Unmarshal(data, &varUserBinPositionTokenWrapper)

	if err != nil {
		return err
	}

	*o = UserBinPositionTokenWrapper(varUserBinPositionTokenWrapper)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address")
		delete(additionalProperties, "name")
		delete(additionalProperties, "symbol")
		delete(additionalProperties, "decimals")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "amountRaw")
		delete(additionalProperties, "price")
		delete(additionalProperties, "priceUsd")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserBinPositionTokenWrapper struct {
	value *UserBinPositionTokenWrapper
	isSet bool
}

func (v NullableUserBinPositionTokenWrapper) Get() *UserBinPositionTokenWrapper {
	return v.value
}

func (v *NullableUserBinPositionTokenWrapper) Set(val *UserBinPositionTokenWrapper) {
	v.value = val
	v.isSet = true
}

func (v NullableUserBinPositionTokenWrapper) IsSet() bool {
	return v.isSet
}

func (v *NullableUserBinPositionTokenWrapper) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserBinPositionTokenWrapper(val *UserBinPositionTokenWrapper) *NullableUserBinPositionTokenWrapper {
	return &NullableUserBinPositionTokenWrapper{value: val, isSet: true}
}

func (v NullableUserBinPositionTokenWrapper) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserBinPositionTokenWrapper) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
