/*
Trader Joe Dex API

<p>Discover DeFi with Trader Joe, a leading decentralized exchange. Trade a wide variety of tokens, earn rewards, and engage in secure, peer-to-peer transactions. Trader Joe makes DeFi easy and accessible.

API version: 1.0.0
Contact: public-api@traderjoexyz.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package traderjoesdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GetVaultToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVaultToken{}

// GetVaultToken struct for GetVaultToken
type GetVaultToken struct {
	Address              string `json:"address"`
	Chain                Chain  `json:"chain"`
	Symbol               string `json:"symbol"`
	Decimals             int32  `json:"decimals"`
	AdditionalProperties map[string]interface{}
}

type _GetVaultToken GetVaultToken

// NewGetVaultToken instantiates a new GetVaultToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVaultToken(address string, chain Chain, symbol string, decimals int32) *GetVaultToken {
	this := GetVaultToken{}
	this.Address = address
	this.Chain = chain
	this.Symbol = symbol
	this.Decimals = decimals
	return &this
}

// NewGetVaultTokenWithDefaults instantiates a new GetVaultToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVaultTokenWithDefaults() *GetVaultToken {
	this := GetVaultToken{}
	return &this
}

// GetAddress returns the Address field value
func (o *GetVaultToken) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *GetVaultToken) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *GetVaultToken) SetAddress(v string) {
	o.Address = v
}

// GetChain returns the Chain field value
func (o *GetVaultToken) GetChain() Chain {
	if o == nil {
		var ret Chain
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *GetVaultToken) GetChainOk() (*Chain, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *GetVaultToken) SetChain(v Chain) {
	o.Chain = v
}

// GetSymbol returns the Symbol field value
func (o *GetVaultToken) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *GetVaultToken) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *GetVaultToken) SetSymbol(v string) {
	o.Symbol = v
}

// GetDecimals returns the Decimals field value
func (o *GetVaultToken) GetDecimals() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Decimals
}

// GetDecimalsOk returns a tuple with the Decimals field value
// and a boolean to check if the value has been set.
func (o *GetVaultToken) GetDecimalsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decimals, true
}

// SetDecimals sets field value
func (o *GetVaultToken) SetDecimals(v int32) {
	o.Decimals = v
}

func (o GetVaultToken) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVaultToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["chain"] = o.Chain
	toSerialize["symbol"] = o.Symbol
	toSerialize["decimals"] = o.Decimals

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetVaultToken) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"chain",
		"symbol",
		"decimals",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetVaultToken := _GetVaultToken{}

	err = json.Unmarshal(data, &varGetVaultToken)

	if err != nil {
		return err
	}

	*o = GetVaultToken(varGetVaultToken)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address")
		delete(additionalProperties, "chain")
		delete(additionalProperties, "symbol")
		delete(additionalProperties, "decimals")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetVaultToken struct {
	value *GetVaultToken
	isSet bool
}

func (v NullableGetVaultToken) Get() *GetVaultToken {
	return v.value
}

func (v *NullableGetVaultToken) Set(val *GetVaultToken) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVaultToken) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVaultToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVaultToken(val *GetVaultToken) *NullableGetVaultToken {
	return &NullableGetVaultToken{value: val, isSet: true}
}

func (v NullableGetVaultToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVaultToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
