/*
Trader Joe Dex API

<p>Discover DeFi with Trader Joe, a leading decentralized exchange. Trade a wide variety of tokens, earn rewards, and engage in secure, peer-to-peer transactions. Trader Joe makes DeFi easy and accessible.

API version: 1.0.0
Contact: public-api@traderjoexyz.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package traderjoesdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GetReward type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetReward{}

// GetReward struct for GetReward
type GetReward struct {
	Id                   string `json:"id"`
	Name                 string `json:"name"`
	Symbol               string `json:"symbol"`
	Decimals             int32  `json:"decimals"`
	AdditionalProperties map[string]interface{}
}

type _GetReward GetReward

// NewGetReward instantiates a new GetReward object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetReward(id string, name string, symbol string, decimals int32) *GetReward {
	this := GetReward{}
	this.Id = id
	this.Name = name
	this.Symbol = symbol
	this.Decimals = decimals
	return &this
}

// NewGetRewardWithDefaults instantiates a new GetReward object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRewardWithDefaults() *GetReward {
	this := GetReward{}
	return &this
}

// GetId returns the Id field value
func (o *GetReward) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetReward) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetReward) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GetReward) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetReward) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetReward) SetName(v string) {
	o.Name = v
}

// GetSymbol returns the Symbol field value
func (o *GetReward) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *GetReward) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *GetReward) SetSymbol(v string) {
	o.Symbol = v
}

// GetDecimals returns the Decimals field value
func (o *GetReward) GetDecimals() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Decimals
}

// GetDecimalsOk returns a tuple with the Decimals field value
// and a boolean to check if the value has been set.
func (o *GetReward) GetDecimalsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decimals, true
}

// SetDecimals sets field value
func (o *GetReward) SetDecimals(v int32) {
	o.Decimals = v
}

func (o GetReward) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetReward) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["symbol"] = o.Symbol
	toSerialize["decimals"] = o.Decimals

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetReward) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"symbol",
		"decimals",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetReward := _GetReward{}

	err = json.Unmarshal(data, &varGetReward)

	if err != nil {
		return err
	}

	*o = GetReward(varGetReward)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "symbol")
		delete(additionalProperties, "decimals")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetReward struct {
	value *GetReward
	isSet bool
}

func (v NullableGetReward) Get() *GetReward {
	return v.value
}

func (v *NullableGetReward) Set(val *GetReward) {
	v.value = val
	v.isSet = true
}

func (v NullableGetReward) IsSet() bool {
	return v.isSet
}

func (v *NullableGetReward) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetReward(val *GetReward) *NullableGetReward {
	return &NullableGetReward{value: val, isSet: true}
}

func (v NullableGetReward) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetReward) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
