/*
Trader Joe Dex API

<p>Discover DeFi with Trader Joe, a leading decentralized exchange. Trade a wide variety of tokens, earn rewards, and engage in secure, peer-to-peer transactions. Trader Joe makes DeFi easy and accessible.

API version: 1.0.0
Contact: public-api@traderjoexyz.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package traderjoesdk

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ChainParam - An enumeration.
type ChainParam struct {
	AllParam *AllParam
	Chain    *Chain
}

// AllParamAsChainParam is a convenience function that returns AllParam wrapped in ChainParam
func AllParamAsChainParam(v *AllParam) ChainParam {
	return ChainParam{
		AllParam: v,
	}
}

// ChainAsChainParam is a convenience function that returns Chain wrapped in ChainParam
func ChainAsChainParam(v *Chain) ChainParam {
	return ChainParam{
		Chain: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ChainParam) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AllParam
	err = newStrictDecoder(data).Decode(&dst.AllParam)
	if err == nil {
		jsonAllParam, _ := json.Marshal(dst.AllParam)
		if string(jsonAllParam) == "{}" { // empty struct
			dst.AllParam = nil
		} else {
			if err = validator.Validate(dst.AllParam); err != nil {
				dst.AllParam = nil
			} else {
				match++
			}
		}
	} else {
		dst.AllParam = nil
	}

	// try to unmarshal data into Chain
	err = newStrictDecoder(data).Decode(&dst.Chain)
	if err == nil {
		jsonChain, _ := json.Marshal(dst.Chain)
		if string(jsonChain) == "{}" { // empty struct
			dst.Chain = nil
		} else {
			if err = validator.Validate(dst.Chain); err != nil {
				dst.Chain = nil
			} else {
				match++
			}
		}
	} else {
		dst.Chain = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AllParam = nil
		dst.Chain = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ChainParam)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ChainParam)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ChainParam) MarshalJSON() ([]byte, error) {
	if src.AllParam != nil {
		return json.Marshal(&src.AllParam)
	}

	if src.Chain != nil {
		return json.Marshal(&src.Chain)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ChainParam) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.AllParam != nil {
		return obj.AllParam
	}

	if obj.Chain != nil {
		return obj.Chain
	}

	// all schemas are nil
	return nil
}

type NullableChainParam struct {
	value *ChainParam
	isSet bool
}

func (v NullableChainParam) Get() *ChainParam {
	return v.value
}

func (v *NullableChainParam) Set(val *ChainParam) {
	v.value = val
	v.isSet = true
}

func (v NullableChainParam) IsSet() bool {
	return v.isSet
}

func (v *NullableChainParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChainParam(val *ChainParam) *NullableChainParam {
	return &NullableChainParam{value: val, isSet: true}
}

func (v NullableChainParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChainParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
