/*
Trader Joe Dex API

<p>Discover DeFi with Trader Joe, a leading decentralized exchange. Trade a wide variety of tokens, earn rewards, and engage in secure, peer-to-peer transactions. Trader Joe makes DeFi easy and accessible.

API version: 1.0.0
Contact: public-api@traderjoexyz.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package traderjoesdk

import (
	"encoding/json"
	"fmt"
)

// PoolSortParam An enumeration.
type PoolSortParam string

// List of PoolSortParam
const (
	LIQUIDITY PoolSortParam = "liquidity"
	NAME      PoolSortParam = "name"
)

// All allowed values of PoolSortParam enum
var AllowedPoolSortParamEnumValues = []PoolSortParam{
	"liquidity",
	"name",
}

func (v *PoolSortParam) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PoolSortParam(value)
	for _, existing := range AllowedPoolSortParamEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PoolSortParam", value)
}

// NewPoolSortParamFromValue returns a pointer to a valid PoolSortParam
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPoolSortParamFromValue(v string) (*PoolSortParam, error) {
	ev := PoolSortParam(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PoolSortParam: valid values are %v", v, AllowedPoolSortParamEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PoolSortParam) IsValid() bool {
	for _, existing := range AllowedPoolSortParamEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PoolSortParam value
func (v PoolSortParam) Ptr() *PoolSortParam {
	return &v
}

type NullablePoolSortParam struct {
	value *PoolSortParam
	isSet bool
}

func (v NullablePoolSortParam) Get() *PoolSortParam {
	return v.value
}

func (v *NullablePoolSortParam) Set(val *PoolSortParam) {
	v.value = val
	v.isSet = true
}

func (v NullablePoolSortParam) IsSet() bool {
	return v.isSet
}

func (v *NullablePoolSortParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePoolSortParam(val *PoolSortParam) *NullablePoolSortParam {
	return &NullablePoolSortParam{value: val, isSet: true}
}

func (v NullablePoolSortParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePoolSortParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
